language: node_js
node_js:
  - 8
before_install:
  - sudo apt-get install -y wine
install:
    - yarn
script:
    - APP_VERSION=v0.1.$TRAVIS_BUILD_NUMBER
    - yarn run build-win
    - zip -r Windows_$APP_VERSION.zip _builds/trello-electron-win32-ia32
before_deploy:
    - git config --local user.name "Grand Silence"
    - git config --local user.email "mixtape774@gmail.com"
    - git tag "$APP_VERSION"
deploy:
  provider: releases
  api_key:
    secure: "gQNL7fDpKToM+7BrGYnH6qADS+lWUW1i6IPBbk1A3a9rIRePwvOoSYS60p4l/iyBLqKLFMmg22fI38OvLDjh76Y0X8fyMnXEi/CD/iY6svleO1aIZgkE45B3CByD9VXI3edp1V1FMT/i4/Kkqy8xtHU9zJ/gbZ+l8LHhEojK6W3+dJRCN1kUow16gIJGg0l6Jsxl8FoZy2tutzTyxA/7zZ1wEIL+XN4SWQWjaFifPSS+Hw26YKaDH/Kh4IZysChFK3lfQH4YxE63rNbPXwyHFHuYVOCfYFAAfSGnTPF4IGbi6pv2Fe6kmDyqSvm2/drCSq5kjPdHLje9OpMHPseIOLz2OvwCQnFpGZOB2oPplVIzUgh80J0bVi9STwneJruLePpdUBKQEN/g9/LGCSEKQ/yeRRN2FG94dyExfei6k9rZNEIp872KbAyvkOr4TNMnQxxe0rsE/Idk8CBSced0prp8ka81vs7OJJkEbqonsv8RYKL7FkKkN/ChrMlXeVM5voa/1uhu1de54m18Qc/8feC5BZJPSAIJFriYZLWXQ2b0ggRhes0d0cVQyRYElvmtrhPNCNlioz0KZ6Zy6tLkPJE4iyQbjApD4E6ST16QCOgb8lFWu3/5draeSlBrZ3+vUtWx8M4Z44MkG3VouLnsraMGF2sfNVgGe9QwSXDjmwM="
  file:
    - "Windows_$APP_VERSION.zip"
  skip_cleanup: true
  on:
    tags: false
    branch: master
branches:
  only:
  - master
skip_commits:
  files:
    - .gitignore
    - jsconfig.json
    - launch.json
    - package.json
    - package-lock.json
    - README.md
    - rebuild_win.bat
cache:
  apt: true
  directories:
    - node_modules
